version: "3.7"
services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rentx
      POSTGRES_PASSWORD: rentx
      POSTGRES_DB: rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app/
    container_name: rentalx

volumes:
  pgdata:
    driver: local
